hash-format = "sha256"

[[files]]
file = "config/DistantHorizons.toml"
hash = "da369f9cfee489aba6fbee5d8b4fcd85d43b334acb1a1461b50c1f774ca059e3"

[[files]]
file = "config/create-client.toml"
hash = "97d26eb70ca8e6e5a48c42c2c73281612192cbb962b0e58d37783708d46c7033"

[[files]]
file = "config/create-common.toml"
hash = "93e7ca6d3bbac4e8c7b7a58ee43432ffe4712472f0238338439b6b3b47e4ee37"

[[files]]
file = "config/create-server.toml"
hash = "147a907c9f3c450094d3b69fc79707c386439520691866ab94fafadd256be156"

[[files]]
file = "config/neoforge-client.toml"
hash = "a5f0eb38f8daf8574f7672a8393a0ab5c668d6ec6e7ae43fc8669e928786929d"

[[files]]
file = "config/neoforge-common.toml"
hash = "e6f7578cf8c11ade0a47e36bf3863fc96f84cdf4bb679c0fceabb1e8a2f42399"

[[files]]
file = "config/neoforge-server.toml"
hash = "0f1415d7fef6d7f6194275501d500b633dd3310aea40d64128edd1b096372f60"

[[files]]
file = "config/voicechat/voicechat-server.properties"
hash = "c40af4fce7e6317fab8297ce3f60e18ffadd59b88726d57ab46f6e8aed0efd63"

[[files]]
file = "mods/c2me.pw.toml"
hash = "ce8e8a52fcf5642ccfe5af600ce3faaadc4aff69e20b604283734bbdc7a24086"
metafile = true

[[files]]
file = "mods/clumps.pw.toml"
hash = "2e6a2f8c477128a76ef059dfef7ca8a1befa2ae0ebe7ae2171e716f0c905cd00"
metafile = true

[[files]]
file = "mods/create-deco.pw.toml"
hash = "9c7b4cd654f026a735240d2d183a9b44e4f5f9ff04a4fc48612a6b82a2230cbb"
metafile = true

[[files]]
file = "mods/create-dragons-plus.pw.toml"
hash = "c6b202693a6def0e9aa2c41d3b7cfbeec473e7c09b8e7754ca786029ff31a4d3"
metafile = true

[[files]]
file = "mods/create-enchantment-industry.pw.toml"
hash = "a1e5a84f5ed75a81e875333433b1ec4239a8b76bf58de669cfcefca924932fab"
metafile = true

[[files]]
file = "mods/create.pw.toml"
hash = "d6043c928c34ce1f4ada544a49193f95c281665cf88d4931e73370ea02870bed"
metafile = true

[[files]]
file = "mods/distant-horizons.pw.toml"
hash = "c40944d53753ca0c91b7ef0d61be499bec8b3cae917a31f33553d1deb8715593"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "4fa1d6b802032c2335bd0f2263e2977b376fd22ee07dc5f57dae9797d0c267d3"
metafile = true

[[files]]
file = "mods/emi.pw.toml"
hash = "1fc8ab07ea6f6abf5252a680f4ee72d7feaa652bc6b17214b1ddc5f5fe4c5d6d"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "3443f52ef7c1f80ae1cedf459b23c38ac78dbe547cf2cc047e62d0cb2331c808"
metafile = true

[[files]]
file = "mods/farmers-delight.pw.toml"
hash = "f407238ae37effcd669f828b80a7246e805bc099b4848cd550b1d2d428fea78b"
metafile = true

[[files]]
file = "mods/ferritecore.pw.toml"
hash = "942b02525962980b6176677cca162d27c1210b686985ad11db0055fe39d42a7d"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "070867dc8ae93744959610974b246cbac214141299710cf7f6e961adb165310a"
metafile = true

[[files]]
file = "mods/irisshaders.pw.toml"
hash = "352bbd56bffa7bb7af6e16ae0e745db85e2d7e9e0ea6037ff866149f6e6e08b8"
metafile = true

[[files]]
file = "mods/jade-addons-forge.pw.toml"
hash = "8cd8400cb4e2c5ba60c8a359a7b6ff501078d2056eab0aba7f6b0ac77b7a0694"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "e7d3f7e0472ba9a3ef946fa5defcb157e4126636e603c2306d4ad6065936d5e2"
metafile = true

[[files]]
file = "mods/just-zoom.pw.toml"
hash = "f565820169e3cd71f18fd0b18eab2405bc400668813d04f3f3eb75b6c8924bcc"
metafile = true

[[files]]
file = "mods/konkrete.pw.toml"
hash = "054a1887da4f14b791910660a2a7a2035ac1382461b881a65fe07b224c03735f"
metafile = true

[[files]]
file = "mods/kotlin-for-forge.pw.toml"
hash = "1a9ec5beaba1be3151b8710db2bfab90c2063a4dafaf2720336852245a145cc4"
metafile = true

[[files]]
file = "mods/krypton-fnp.pw.toml"
hash = "e5e4c1204b278535538d4e45b3c65e577b37cfb3c17ebae5d136404d6b37fbfb"
metafile = true

[[files]]
file = "mods/ksyxis.pw.toml"
hash = "885976c7e80d47800b5fe6dc614097772cc88f908160abd50fcdebcda7e1270c"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "908cbf89e774b114d1dc3aef4806c9d2d782cfd314be001718bb690af9b074a8"
metafile = true

[[files]]
file = "mods/neoforge-carpet.pw.toml"
hash = "7513ef48054b3d2d72aace3d3f39440c6b533ba518ea8d4cfaf1fb6d30dd9e7d"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "5da18814472be5dc93a21886983646da3a7236413800075ac75229be82d114fa"
metafile = true

[[files]]
file = "mods/remove-terralith-intro-message.pw.toml"
hash = "fe85eb7e13d32999eb376d154be220d82134c534a3f066fa263fb4af11535232"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "82fa5e74cae0b3f0199f9822f62a976da2dc6ee03deb543d537ce55d36b11fcb"
metafile = true

[[files]]
file = "mods/slice-and-dice.pw.toml"
hash = "97658372a06b324c2121668e350cd27b02428db882f7f4943182aeef3f4cca75"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "b16ee8ff10576cf6ef43fd6a2828463faf96de88e6409f9ee6b3dd31645d282d"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "8d5628a4af0f355519b17bb0c6e5783c30aa78f6aa04b77b3892cd5d7c10af03"
metafile = true

[[files]]
file = "mods/sophisticated-backpacks.pw.toml"
hash = "a2028f1fdc803760a29877b07b2958cecdc6402eb946f9d5a0fff9fe72b8671d"
metafile = true

[[files]]
file = "mods/sophisticated-core.pw.toml"
hash = "8ed3c58f23d9255343a590b90e1216ac58142b920c9bffdd14c7fdc32e3ee002"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
hash = "593fa7b30ab016aa45be07bd6bef3a9f160ed0f24689850d60bf84995d69b843"
metafile = true

[[files]]
file = "mods/terralith.pw.toml"
hash = "da7ee99189ad35aac094919fe33cac647d98533b23c228f10d4811f08989e2b8"
metafile = true

[[files]]
file = "options.txt"
hash = "f36f4e82e81110e5ade9964b09c08a3a38fa9fdf4696ced885f8dd101f0c9f10"
