hash-format = "sha256"

[[files]]
file = ".direnv/bin/nix-direnv-reload"
hash = "d265e1e846b16c90d5f45c03b8a79e77798c7cf4b5ba493586a543d6bc7faa6b"

[[files]]
file = ".direnv/nix-profile-pre782598.18dd725c2960"
hash = "e86164cb182c12aeaaaf6424c17a47defba1f6c421dc573613548f9f39259135"

[[files]]
file = ".direnv/nix-profile-pre782598.18dd725c2960.rc"
hash = "6200a5f401dcfca15c7341f3dc76f2eb2fabb5095666a20f281233c840bf3ab8"

[[files]]
file = ".envrc"
hash = "5aa3cd865fb13cb88c1d749614b53120a92d16a922fe89a3009b0552097926a0"

[[files]]
file = ".jj/repo/index/op_links/00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
hash = "cbd2f459d90e73aca76dd891ab9de0154dfaf7a48b36c65b4880c830a193675c"

[[files]]
file = ".jj/repo/index/op_links/00f9999edbcc3d9907bb2eed448dfe14e4c57d8574666600f63a6c1df10f78ed6e79e0b40c6891583872e70ff4cca67400d927f2e52a1b4c802212a3c567322c"
hash = "249606e69a9fa7a52ea538fd7282308661918d1aa2f00353a49d8e4bff3e16a9"

[[files]]
file = ".jj/repo/index/op_links/4522267fda7b13e78ca353c239d383b9fc0fd04a6261b30af1687b51a1038ca1a3f1f8085dff91861d9f51ef9400516b3213e2204e02bc9afac4ee4629fbdce2"
hash = "d4a2e235eab241fac59f90c7a0d5aa50acfb368c6638fa0d4b2cfa04244159ed"

[[files]]
file = ".jj/repo/index/op_links/eedf8e9bbea9c6c32d4d1f95d737bc5ab466bb3282c258e2e24b47bd70821bca3920f2b037d227b117a10f74642fd3325d33b394788f803bde2b2b3ae2b3a45f"
hash = "1a8c989e1321a1b557bed53d2279671eec19171eaed05918b94d8c5cb24195b5"

[[files]]
file = ".jj/repo/index/operations/00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
hash = "80bdd39f21255eccfe2e60635bed5c0d038cfc17ac50f2991142b0fc2e83379c"

[[files]]
file = ".jj/repo/index/operations/00f9999edbcc3d9907bb2eed448dfe14e4c57d8574666600f63a6c1df10f78ed6e79e0b40c6891583872e70ff4cca67400d927f2e52a1b4c802212a3c567322c"
hash = "d6dfc5e5573d7ef0b68e83814947a5b1488ddb6eee3f54821b65a0d6a0ca4202"

[[files]]
file = ".jj/repo/index/operations/4522267fda7b13e78ca353c239d383b9fc0fd04a6261b30af1687b51a1038ca1a3f1f8085dff91861d9f51ef9400516b3213e2204e02bc9afac4ee4629fbdce2"
hash = "75d197e2d22cab4a0d17bbcec335a17a3e602a64d73f173b375f1974c1f77189"

[[files]]
file = ".jj/repo/index/operations/eedf8e9bbea9c6c32d4d1f95d737bc5ab466bb3282c258e2e24b47bd70821bca3920f2b037d227b117a10f74642fd3325d33b394788f803bde2b2b3ae2b3a45f"
hash = "3b0bab38cdc00cbbb4018a6ac09cf68242b6abcc6405c3d04412e63336253bad"

[[files]]
file = ".jj/repo/index/segments/0b39ca8ff751962eb8ccd57c6083f142360ed6ea2b2c58d9f4caf78f59241e510534cd1ad13b6301fb916c747168f22c47dc9cdf35594602539e7a91100d4b91"
hash = "e54d6958182756a3ff694ee06869a5b4663c0de5744894a899a8363c5d6bbe0f"

[[files]]
file = ".jj/repo/index/segments/a7fb7cc801cd2db01a9a483ef213ccd10171de4fab83c4c6411e95374be6c95d10fee1295ac09506188e90d50c997091f76a008f655ebafe8d1b537362a60a60"
hash = "8e0235d6505255371d2e67151eb6db160f64032ce96280cfd345698294f6ce83"

[[files]]
file = ".jj/repo/index/segments/d27ad326963b75736b636adad9fb812eb3f2871e0efb4bc7db37d4b701a4282911eaaee91bed3a759e940769b667be1ed66f2d7f2f41ac3906b87ab7eec19c3a"
hash = "7dded0d7539a893e0a1314dd270a4c166b9e7d7b034255c27b4c6893f3fdbbc5"

[[files]]
file = ".jj/repo/index/segments/d280c9e4b384ac83c0d73bbf7ffb736ebd92a3c8961a60c102bfb5c77be4401b82c8a02e80635daed826926ed5ad926b721e3ffd1144cbb3fb6461bcef9f80c4"
hash = "8ed51158b2dc0794d702e6e2e33b6196d2aca02195e4e3f6f534052e7878435e"

[[files]]
file = ".jj/repo/index/type"
hash = "37a8eec1ce19687d132fe29051dca629d164e2c4958ba141d5f4133a33f0688f"

[[files]]
file = ".jj/repo/op_heads/heads/4522267fda7b13e78ca353c239d383b9fc0fd04a6261b30af1687b51a1038ca1a3f1f8085dff91861d9f51ef9400516b3213e2204e02bc9afac4ee4629fbdce2"
hash = "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"

[[files]]
file = ".jj/repo/op_heads/type"
hash = "b033b33ef05b48b699b625dd905e19e3ad154d4c9a393f0623e60d6179a233b8"

[[files]]
file = ".jj/repo/op_store/operations/00f9999edbcc3d9907bb2eed448dfe14e4c57d8574666600f63a6c1df10f78ed6e79e0b40c6891583872e70ff4cca67400d927f2e52a1b4c802212a3c567322c"
hash = "35eb519a857093f6b0f1ecab4aaeb0c580e2569bf1fe1499bb871946fa36f8ab"

[[files]]
file = ".jj/repo/op_store/operations/4522267fda7b13e78ca353c239d383b9fc0fd04a6261b30af1687b51a1038ca1a3f1f8085dff91861d9f51ef9400516b3213e2204e02bc9afac4ee4629fbdce2"
hash = "ebdbd69522c9ca65b5104846c9ba4a1f0cd7cab7821e53f0b4145147ff121f65"

[[files]]
file = ".jj/repo/op_store/operations/eedf8e9bbea9c6c32d4d1f95d737bc5ab466bb3282c258e2e24b47bd70821bca3920f2b037d227b117a10f74642fd3325d33b394788f803bde2b2b3ae2b3a45f"
hash = "0ded92317550fdc91bf48054899405c16a72987890297f60508047d0399c55d2"

[[files]]
file = ".jj/repo/op_store/type"
hash = "ed58fb26ed304558ff125ef841b4ba29b7b0d94b810f1c5428312114ac4a0c1b"

[[files]]
file = ".jj/repo/op_store/views/4a71f2f626f944479f40e146b5ff94356a680f3c0f58fd2fa4764129ba9566151aff99b8b0201e027de3e0dbacc14a28d3bada2d3257d8aab4911df36a31062a"
hash = "7d654335cc57c400d8212e0ca54e1432a636fc62e6ba6f8c96f9343120b7dd90"

[[files]]
file = ".jj/repo/op_store/views/c03bcb106da61921407a1964bd3d5c366e68c9b4fc33a0abe431850f769356f9c68cf6572ef01fd1eb09d2b8a947bc4696b8b88637e19ddac29d5869e377cbb5"
hash = "a892789932e62693f03dd519e1c3a60a3d3a502b306a8fdd1eed78c360375b60"

[[files]]
file = ".jj/repo/op_store/views/ef15038edb90c6e7f36bbadfb4261eef99fd9b1307a3b133c754931eadd15c175e3fc633464811a45a5310242f68bfcfec6e2e5f7e6dadf7f219d4ef7b2ecf8e"
hash = "ef99e0c393ee9ec832d5dd9dcc396a98384a4aeeb80e143f57ead918affc6151"

[[files]]
file = ".jj/repo/store/extra/23e7b6174dbaf78bfdff852dde28d8f8c4b9f056b68e903859f8432f78967bbc653fd12c39756465640c3aa54897b72385e3f4205ed10f51c5b54e636a5c8ec2"
hash = "6c137ac75cb14d66921c9b710e89e127e549140781cd69f184e3f7d06b6e6791"

[[files]]
file = ".jj/repo/store/extra/39276a4f0f0a80cb94301b03a231310078be236831e6187396ae2b87679194ac5a53e9a49baa078572d74da12a765b609bfd4d695af251daba27a06e1c467dde"
hash = "22538cec59fa5d8fe37a0a28e4d5a57ea90b535ef9de2ca17ad09e5fb38690a7"

[[files]]
file = ".jj/repo/store/extra/39886fec4ffb7e2203201f28f3f8a92f5a74d166d4ea0685b26165b353e61cd4624cbef68f3ea65703d33c3e1660ac504eaa481504aa36e5b8a0a0c24bc35e96"
hash = "344100730de858c300d59f71e28a7bbaf6d4964da6232489887b92c497377287"

[[files]]
file = ".jj/repo/store/extra/482ae5a29fbe856c7272f2071b8b0f0359ee2d89ff392b8a900643fbd0836eccd067b8bf41909e206c90d45d6e7d8b6686b93ecaee5fe1a9060d87b672101310"
hash = "af5570f5a1810b7af78caf4bc70a660f0df51e42baf91d4de5b2328de0e83dfc"

[[files]]
file = ".jj/repo/store/extra/heads/39276a4f0f0a80cb94301b03a231310078be236831e6187396ae2b87679194ac5a53e9a49baa078572d74da12a765b609bfd4d695af251daba27a06e1c467dde"
hash = "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"

[[files]]
file = ".jj/repo/store/git_target"
hash = "6fce35d09d036a8aa687ec5aface9db45921166ea3bd2615c775afbb199a9d96"

[[files]]
file = ".jj/repo/store/type"
hash = "9a881b9b9f23849475296a8cd768ea1965bc3152df7118e60c145975af6aa58a"

[[files]]
file = ".jj/repo/submodule_store/type"
hash = "37a8eec1ce19687d132fe29051dca629d164e2c4958ba141d5f4133a33f0688f"

[[files]]
file = ".jj/working_copy/checkout"
hash = "c548fd48e9eb8816cd33206e3c6001b9d84bd841d4fd12a6e9c0fae041c10746"

[[files]]
file = ".jj/working_copy/tree_state"
hash = "a18867a9e7d806e3007b8c902b2b2bbb8ae55d3d9db2f367254840b22b19d586"

[[files]]
file = ".jj/working_copy/type"
hash = "25bf8e1a2393f1108d37029b3df5593236c755742ec93465bbafa9b290bddcf6"

[[files]]
file = "config/DistantHorizons.toml"
hash = "da369f9cfee489aba6fbee5d8b4fcd85d43b334acb1a1461b50c1f774ca059e3"

[[files]]
file = "config/c2me.toml"
hash = "1b5e3062fabc38ca5cd3c2e5543359337f4f50b8cc9a6398779d844f9247b617"

[[files]]
file = "config/create-client.toml"
hash = "97d26eb70ca8e6e5a48c42c2c73281612192cbb962b0e58d37783708d46c7033"

[[files]]
file = "config/create-common.toml"
hash = "93e7ca6d3bbac4e8c7b7a58ee43432ffe4712472f0238338439b6b3b47e4ee37"

[[files]]
file = "config/create-server.toml"
hash = "147a907c9f3c450094d3b69fc79707c386439520691866ab94fafadd256be156"

[[files]]
file = "config/dynamic_fps.json"
hash = "ca3d163bab055381827226140568f3bef7eaac187cebd76878e0b63e9e442356"

[[files]]
file = "config/emi.css"
hash = "ef29ffa364bb9d68611e126c57a99c3a0aa29f3c080dd935ffbcd66cf17691e6"

[[files]]
file = "config/entityculling.json"
hash = "5110d83fa12df053d48eb3bcfded9d174e617910ce3e6c72f01dfc248c4e6abb"

[[files]]
file = "config/ferritecore-mixin.toml"
hash = "4d9bed5dbfa06cd545c9f56db4fd4f0c268651e06a5dd8039b16ba2a307f4c03"

[[files]]
file = "config/flywheel-client.toml"
hash = "9a8019a2819cf8f27a30c0788b458ed7e9b6d749faea23d8feafa0424c4bb568"

[[files]]
file = "config/fml.toml"
hash = "cc127c6067eb9e23289edc1c774afd71456456eef06c688af6731a72d3bba5e5"

[[files]]
file = "config/immediatelyfast.json"
hash = "f2b7f219198f0a911d04b09f545f2c1256e8d114951443924878dc10963e16aa"

[[files]]
file = "config/iris-excluded.json"
hash = "4d3264b58c502afaeca3f44e8d2db0843c54b8ba957afd21a2d450fe10dafefb"

[[files]]
file = "config/iris.properties"
hash = "750bb24c245f8ebb156b8017540a45b79e5936b41c0d2b019121f8a72c92799c"

[[files]]
file = "config/krypton_fnp.yaml"
hash = "7fc09d9dddee0f2524d80d59640958c45c21e0a1aa7f66eac7666d25f6a64886"

[[files]]
file = "config/neoforge-client.toml"
hash = "a5f0eb38f8daf8574f7672a8393a0ab5c668d6ec6e7ae43fc8669e928786929d"

[[files]]
file = "config/neoforge-common.toml"
hash = "e6f7578cf8c11ade0a47e36bf3863fc96f84cdf4bb679c0fceabb1e8a2f42399"

[[files]]
file = "config/neoforge-server.toml"
hash = "0f1415d7fef6d7f6194275501d500b633dd3310aea40d64128edd1b096372f60"

[[files]]
file = "config/ponder-client.toml"
hash = "fd509f0bd365af92e54bbd8fda3bbd883f4c76fc9068408ebfa16bf6820ba30b"

[[files]]
file = "config/sliceanddice-client.toml"
hash = "765cd3bbbdd6ac865481befc841cf5a494412927d91857eb7561b213aad424d2"

[[files]]
file = "config/sliceanddice-common.toml"
hash = "76d1cc946bd3b2ee86c9b155c183264bc37f5cee248c77c2e990b3a0a34d3739"

[[files]]
file = "config/voicechat/category-volumes.properties"
hash = "3747c48bcb3a60834f88f056ee9b3a025153b11f6ca88652b4bddebb77cea009"

[[files]]
file = "config/voicechat/player-volumes.properties"
hash = "cd385ca1eeda4df612631e2713cc6d503793157ef8bd5518d736429e6c1ae474"

[[files]]
file = "config/voicechat/translations.properties"
hash = "b258a94a5ed60fbf93b66c452c3d6e36b044f630741f90e5b13852a4805b235e"

[[files]]
file = "config/voicechat/voicechat-server.properties"
hash = "c40af4fce7e6317fab8297ce3f60e18ffadd59b88726d57ab46f6e8aed0efd63"

[[files]]
file = "mods/c2me.pw.toml"
hash = "ce8e8a52fcf5642ccfe5af600ce3faaadc4aff69e20b604283734bbdc7a24086"
metafile = true

[[files]]
file = "mods/chunky.pw.toml"
hash = "1d5cc2b6dcfd1fc3adba4566b1c29b57ff1175316678c1f22e63cbc3e28a5ba0"
metafile = true

[[files]]
file = "mods/clumps.pw.toml"
hash = "2e6a2f8c477128a76ef059dfef7ca8a1befa2ae0ebe7ae2171e716f0c905cd00"
metafile = true

[[files]]
file = "mods/create-deco.pw.toml"
hash = "9c7b4cd654f026a735240d2d183a9b44e4f5f9ff04a4fc48612a6b82a2230cbb"
metafile = true

[[files]]
file = "mods/create-dragons-plus.pw.toml"
hash = "c6b202693a6def0e9aa2c41d3b7cfbeec473e7c09b8e7754ca786029ff31a4d3"
metafile = true

[[files]]
file = "mods/create-enchantment-industry.pw.toml"
hash = "a1e5a84f5ed75a81e875333433b1ec4239a8b76bf58de669cfcefca924932fab"
metafile = true

[[files]]
file = "mods/create.pw.toml"
hash = "eb7b4a7b28d4806c7bb7a0cf84f4dca90fc5d62317573e9100542bc484a48750"
metafile = true

[[files]]
file = "mods/distant-horizons.pw.toml"
hash = "c40944d53753ca0c91b7ef0d61be499bec8b3cae917a31f33553d1deb8715593"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "4fa1d6b802032c2335bd0f2263e2977b376fd22ee07dc5f57dae9797d0c267d3"
metafile = true

[[files]]
file = "mods/emi.pw.toml"
hash = "1fc8ab07ea6f6abf5252a680f4ee72d7feaa652bc6b17214b1ddc5f5fe4c5d6d"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "06e87d3cc5ee6a1f467160d2cb8e416f42aaa2c4271adb380c2672f4f4cac9c8"
metafile = true

[[files]]
file = "mods/farmers-delight.pw.toml"
hash = "f407238ae37effcd669f828b80a7246e805bc099b4848cd550b1d2d428fea78b"
metafile = true

[[files]]
file = "mods/ferritecore.pw.toml"
hash = "942b02525962980b6176677cca162d27c1210b686985ad11db0055fe39d42a7d"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "070867dc8ae93744959610974b246cbac214141299710cf7f6e961adb165310a"
metafile = true

[[files]]
file = "mods/irisshaders.pw.toml"
hash = "352bbd56bffa7bb7af6e16ae0e745db85e2d7e9e0ea6037ff866149f6e6e08b8"
metafile = true

[[files]]
file = "mods/kotlinforforge-5.10.0-all.jar"
hash = "3f6e1d0e34c86e62abce3a9f86764a6861a2101aaa8858ada9d81f4588336efe"

[[files]]
file = "mods/krypton-fnp.pw.toml"
hash = "f943a9fe17d0aab797d6d252ff9249a0c3b0cba476dbd03af258336c6f12b8b5"
metafile = true

[[files]]
file = "mods/ksyxis.pw.toml"
hash = "885976c7e80d47800b5fe6dc614097772cc88f908160abd50fcdebcda7e1270c"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "908cbf89e774b114d1dc3aef4806c9d2d782cfd314be001718bb690af9b074a8"
metafile = true

[[files]]
file = "mods/slice-and-dice.pw.toml"
hash = "97658372a06b324c2121668e350cd27b02428db882f7f4943182aeef3f4cca75"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "b16ee8ff10576cf6ef43fd6a2828463faf96de88e6409f9ee6b3dd31645d282d"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "8d5628a4af0f355519b17bb0c6e5783c30aa78f6aa04b77b3892cd5d7c10af03"
metafile = true

[[files]]
file = "mods/sophisticatedbackpacks-1.21.1-3.25.14.1410.jar"
hash = "917f758c23965aa8a7573bfdd638995b92473c6a98802ffffc533720cb4f4aa5"

[[files]]
file = "mods/sophisticatedcore-1.21.1-1.3.89.1239.jar"
hash = "4b38cfdd6cf8a0b7af7665611b0c5d5d85d062f1433e4c20dcbf6dd31132d638"

[[files]]
file = "mods/sound-physics-remastered-neoforge-1.21.1-1.5.1.jar"
hash = "bddc71ecd4f074a101eb3785599d13c69e64025e1029aa0fd0a28fcf9bccf2ea"

[[files]]
file = "mods/terralith.pw.toml"
hash = "0e02e93b9468dca005f7fea385e92612e38bb6807f4dcd64ce7a4b22fac78581"
metafile = true

[[files]]
file = "mods/voicechat-neoforge-1.21.1-2.6.6.jar"
hash = "d6b030f5e217d904aaca29c6e6f1a6b7365be6931db0bd7632e6385805b498b1"

[[files]]
file = "npins/default.nix"
hash = "7a013995924177fdc2ca265253bdeb2b29bece38c6d7bc1d0cf3416a3ae3a33f"

[[files]]
file = "npins/sources.json"
hash = "a83a87e05aaf165b4a1007f4955b0f6a6b17e68f7fd8d360d848d1e08bc4302f"

[[files]]
file = "options.txt"
hash = "f36f4e82e81110e5ade9964b09c08a3a38fa9fdf4696ced885f8dd101f0c9f10"

[[files]]
file = "shell.nix"
hash = "71b9bc84f8a2f04a0eba2da16c149944c7d666b9e927d98b5d79fb35dc70fc06"
