hash-format = "sha256"

[[files]]
file = "config/DistantHorizons.toml"
hash = "a004493256ef90adbef55a1eb566ec7f3de1cddec32c47c671fae683fef25c06"

[[files]]
file = "config/bluemap/core.conf"
hash = "ca2bb1322ae9e4f538a35ed72d1c01495e0fcd4b837692a720804120eebe1b26"

[[files]]
file = "config/create-client.toml"
hash = "97d26eb70ca8e6e5a48c42c2c73281612192cbb962b0e58d37783708d46c7033"

[[files]]
file = "config/create-common.toml"
hash = "93e7ca6d3bbac4e8c7b7a58ee43432ffe4712472f0238338439b6b3b47e4ee37"

[[files]]
file = "config/create-server.toml"
hash = "147a907c9f3c450094d3b69fc79707c386439520691866ab94fafadd256be156"

[[files]]
file = "config/emi.css"
hash = "d78ad89a486b23def92bed4e3a529c1980a0f0f4893036732bdd5d299a61e460"

[[files]]
file = "config/modernfix-mixins.properties"
hash = "dc92fe2e6154e7a9883eb62b4183f4415ac9131a043d250c211d2ce684e3f85b"

[[files]]
file = "config/neoforge-client.toml"
hash = "a5f0eb38f8daf8574f7672a8393a0ab5c668d6ec6e7ae43fc8669e928786929d"

[[files]]
file = "config/neoforge-common.toml"
hash = "e6f7578cf8c11ade0a47e36bf3863fc96f84cdf4bb679c0fceabb1e8a2f42399"

[[files]]
file = "config/neoforge-server.toml"
hash = "0f1415d7fef6d7f6194275501d500b633dd3310aea40d64128edd1b096372f60"

[[files]]
file = "config/voicechat/voicechat-server.properties"
hash = "c40af4fce7e6317fab8297ce3f60e18ffadd59b88726d57ab46f6e8aed0efd63"

[[files]]
file = "mods/3dskinlayers.pw.toml"
hash = "7b5fba1b2499c191160be6b1b01c54ace077ae7d3c5228ae4af4d360e3d0a336"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "3213c881d019cd8f952f738c10d5a950ee52ff0084750b81f656a58a4a78515d"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "ea336d25c3e21ef168aec20e1ea470c96949ad29632646ee8e8ab0d74b4bbfc9"
metafile = true

[[files]]
file = "mods/bluemap.pw.toml"
hash = "f33a4720ef4f315b6d1f778039e9f7bdb8f5ef1b58a57d565c30fd1d8adee207"
metafile = true

[[files]]
file = "mods/c2me.pw.toml"
hash = "ffb32b95015187bb5fd6e4da021a2bc636bdabb29a6917c992c4344d9163e8fb"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
hash = "8629fe0739a2243641a1a00b103682bcb2741a9295f9eac4c2a2135a867f8442"
metafile = true

[[files]]
file = "mods/clumps.pw.toml"
hash = "2e6a2f8c477128a76ef059dfef7ca8a1befa2ae0ebe7ae2171e716f0c905cd00"
metafile = true

[[files]]
file = "mods/create-deco.pw.toml"
hash = "9c7b4cd654f026a735240d2d183a9b44e4f5f9ff04a4fc48612a6b82a2230cbb"
metafile = true

[[files]]
file = "mods/create-dragons-plus.pw.toml"
hash = "40ef901fad34e97d592aa27990328b3cfc3864fdac551ec654eee203fb084897"
metafile = true

[[files]]
file = "mods/create-enchantment-industry.pw.toml"
hash = "5911c36695128b20ab3bbbf41adbab0b29f4dff7f6db1eed803a847568a6155c"
metafile = true

[[files]]
file = "mods/create-goggles.pw.toml"
hash = "5de2bbab0826b5241e16746b0b739ca5169b0a9df38181d58e8519e6ea7f535f"
metafile = true

[[files]]
file = "mods/create-ultimate-factory.pw.toml"
hash = "183370d2f76530fd297ec977f6e2941073fe6e0e9b9f8486cf5adc9956c6310e"
metafile = true

[[files]]
file = "mods/create.pw.toml"
hash = "d6043c928c34ce1f4ada544a49193f95c281665cf88d4931e73370ea02870bed"
metafile = true

[[files]]
file = "mods/display-delight.pw.toml"
hash = "28f531c7efc9e5257235adcb19913ed278f3bc76a36326f28d9fb9303df9e4de"
metafile = true

[[files]]
file = "mods/distant-horizons.pw.toml"
hash = "c40944d53753ca0c91b7ef0d61be499bec8b3cae917a31f33553d1deb8715593"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "4fa1d6b802032c2335bd0f2263e2977b376fd22ee07dc5f57dae9797d0c267d3"
metafile = true

[[files]]
file = "mods/emi.pw.toml"
hash = "1fc8ab07ea6f6abf5252a680f4ee72d7feaa652bc6b17214b1ddc5f5fe4c5d6d"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "3443f52ef7c1f80ae1cedf459b23c38ac78dbe547cf2cc047e62d0cb2331c808"
metafile = true

[[files]]
file = "mods/farmers-delight.pw.toml"
hash = "f407238ae37effcd669f828b80a7246e805bc099b4848cd550b1d2d428fea78b"
metafile = true

[[files]]
file = "mods/fast-ip-ping.pw.toml"
hash = "2741b6724a6c7d625c1c9e647a8d20ab89cd4a3975c18706da30771754c00510"
metafile = true

[[files]]
file = "mods/ferritecore.pw.toml"
hash = "942b02525962980b6176677cca162d27c1210b686985ad11db0055fe39d42a7d"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "070867dc8ae93744959610974b246cbac214141299710cf7f6e961adb165310a"
metafile = true

[[files]]
file = "mods/irisshaders.pw.toml"
hash = "352bbd56bffa7bb7af6e16ae0e745db85e2d7e9e0ea6037ff866149f6e6e08b8"
metafile = true

[[files]]
file = "mods/jade-addons-forge.pw.toml"
hash = "8cd8400cb4e2c5ba60c8a359a7b6ff501078d2056eab0aba7f6b0ac77b7a0694"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "e7d3f7e0472ba9a3ef946fa5defcb157e4126636e603c2306d4ad6065936d5e2"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
hash = "635e0d0eba66fcc6eb94026dfa562742d5b6aa96b8f316d0ed1b1678049b54b0"
metafile = true

[[files]]
file = "mods/just-zoom.pw.toml"
hash = "f565820169e3cd71f18fd0b18eab2405bc400668813d04f3f3eb75b6c8924bcc"
metafile = true

[[files]]
file = "mods/konkrete.pw.toml"
hash = "054a1887da4f14b791910660a2a7a2035ac1382461b881a65fe07b224c03735f"
metafile = true

[[files]]
file = "mods/kotlin-for-forge.pw.toml"
hash = "1a9ec5beaba1be3151b8710db2bfab90c2063a4dafaf2720336852245a145cc4"
metafile = true

[[files]]
file = "mods/krypton-fnp.pw.toml"
hash = "e5e4c1204b278535538d4e45b3c65e577b37cfb3c17ebae5d136404d6b37fbfb"
metafile = true

[[files]]
file = "mods/ksyxis.pw.toml"
hash = "885976c7e80d47800b5fe6dc614097772cc88f908160abd50fcdebcda7e1270c"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "b8ce87d9a7164676e68e69e9e6706cd6e9123b1fe740612b1ba39b43ce8675ef"
metafile = true

[[files]]
file = "mods/modelfix.pw.toml"
hash = "6f0dcbcffd4400c6cef07f1eeb48cdc25bac0fa01270936feab4c549aff4738e"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "eae3c14c915400de36bf547550f630de727bbf48ae0ce719b99b2ff50ceaab0d"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "6bc414cc0f2d4c078fe83f384d786343f701f371d657c5279b5b0df1595804bd"
metafile = true

[[files]]
file = "mods/neoforge-carpet.pw.toml"
hash = "7513ef48054b3d2d72aace3d3f39440c6b533ba518ea8d4cfaf1fb6d30dd9e7d"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "5da18814472be5dc93a21886983646da3a7236413800075ac75229be82d114fa"
metafile = true

[[files]]
file = "mods/noisium.pw.toml"
hash = "d424a9260ef51bc102e56f0423d91dfabb739ccca8a86eb1c450ea631b739280"
metafile = true

[[files]]
file = "mods/remove-terralith-intro-message.pw.toml"
hash = "fe85eb7e13d32999eb376d154be220d82134c534a3f066fa263fb4af11535232"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "82fa5e74cae0b3f0199f9822f62a976da2dc6ee03deb543d537ce55d36b11fcb"
metafile = true

[[files]]
file = "mods/slice-and-dice.pw.toml"
hash = "97658372a06b324c2121668e350cd27b02428db882f7f4943182aeef3f4cca75"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "b16ee8ff10576cf6ef43fd6a2828463faf96de88e6409f9ee6b3dd31645d282d"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "8d5628a4af0f355519b17bb0c6e5783c30aa78f6aa04b77b3892cd5d7c10af03"
metafile = true

[[files]]
file = "mods/sophisticated-backpacks.pw.toml"
hash = "a2028f1fdc803760a29877b07b2958cecdc6402eb946f9d5a0fff9fe72b8671d"
metafile = true

[[files]]
file = "mods/sophisticated-core.pw.toml"
hash = "8ed3c58f23d9255343a590b90e1216ac58142b920c9bffdd14c7fdc32e3ee002"
metafile = true

[[files]]
file = "mods/sound-physics-remastered.pw.toml"
hash = "258a77de0a6db4c9ab045cbb240bcf4eac0dbbca3f6bc981fb461e55c247f23f"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
hash = "5995decc8738d7ddccec218dfa1ed95db9eca5bb64c98fd2cede8bf9bbc837c2"
metafile = true

[[files]]
file = "mods/terralith.pw.toml"
hash = "da7ee99189ad35aac094919fe33cac647d98533b23c228f10d4811f08989e2b8"
metafile = true

[[files]]
file = "options.txt"
hash = "f36f4e82e81110e5ade9964b09c08a3a38fa9fdf4696ced885f8dd101f0c9f10"

[[files]]
file = "servers.dat"
hash = "3e664877b67722f376c00f2f4a8e2d5575a09c810e7d035821356d09c9c8b335"

[[files]]
file = "shaderpacks/complementary-reimagined.pw.toml"
hash = "531a8d239c952428d9a633ff99cb03461656ada28decbe2e1ef19f60f7fd5726"
metafile = true
