name = "Forgettable Create"
author = "marshmallow"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fa3a7b1c04eb6b8eb31110d3a367992a0a0f8b1a757b3ab27b5f7d95b88ad1d9"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.214"
