name = "Forgettable Create"
author = "marshmallow"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "332751f0b9e29625725f47ba6635d425d9ac3cf4d71cc2cb9c82b278efa3da12"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.214"
