name = "Forgettable Create"
author = "marshmallow"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "be4237627398f87f086a2e1c53fe14982ea5f79ce424e6bd6c4a7098c37bfb1f"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.214"
