name = "Forgettable Create"
author = "marshmallow"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "058049d35f9f6560213ceb43db020281436a62500034f6986251c32b97e58dca"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.214"
