name = "Forgettable Create"
author = "marshmallow"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "089100c35a0f7ddf9cf701d23b939f8c0d665f42739e7f6a4c3d4f2dec9a422b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.214"
