name = "Forgettable Create"
author = "marshmallow"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "caf5a7b32e7ad4cf2f69dd59fcd9504b9a33c4e44b0c27c5ebc1526a9ff4e9b5"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.214"
