name = "Forgettable Create"
author = "marshmallow"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "288af70abde2ad23aaa78a0ebe103cc1f18d9954f1f26af6fff8223eb4c98791"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.214"
