name = "Forgettable Create"
author = "marshmallow"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "95ce09492b57b08afabef126893dbc4d3978dba9a8d51a4ccf8ea41bb2b20baf"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.214"
