name = "Forgettable Create"
author = "marshmallow"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0707983e5ec5fba18218b821531fea10396a93704793cd306fb1aff01a22d899"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.214"
