name = "Forgettable Create"
author = "marshmallow"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "29ae98973afa4aee6cc1cf1988322f93786cca4c31a4a1f408de7075fa2227b1"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.214"
