name = "Forgettable Create"
author = "marshmallow"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8628cfad1594968ad099091c8d5ff92205afe65b369c489e41be2badbf4f63d0"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.214"
