name = "Forgettable Create"
author = "marshmallow"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "545a148662e9cb9dec3a4ab6f13c46460cd73aca5a19598832c15c0c19dadfe2"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.214"
