name = "Forgettable Create"
author = "marshmallow"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "49936fac35b0d42b74d49ef7d4d5cf74718d608660b296cf3ec64b9d40187ff0"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.214"
